version: "3.8"

services:
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:      
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432