-- CreateEnum
CREATE TYPE "TrialStudentStatus" AS ENUM ('SCHEDULED', 'PENDING_STATUS', 'CONVERTED', 'NOT_CONVERTED', 'RESCHEDULED', 'CANCELLED');

-- AlterTable
ALTER TABLE "trial_students" ADD COLUMN     "status" "TrialStudentStatus" NOT NULL DEFAULT 'SCHEDULED',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
